apiVersion: v1
kind: Service
metadata:
  name: webservice-clusterip
spec:
  selector:
    app: webservice
  ports:
    - protocol: TCP
      port: 5090
      targetPort: 5090

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webservice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webservice-clusterip
            port:
              number: 5090