---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-uos-data
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-app-data
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
