apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-applications
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 1
  source:
    repoURL: https://github.com/lukashankeln/Homelab.git
    targetRevision: feat/create-helm-chart-webapplication
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true