apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deployment-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/lukashankeln/Homelab.git
        revision: HEAD
        directories:
          - path: kubernetes/*
  template:
    metadata:
      name: "deploy-{{.path.basename | lower}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/lukashankeln/Homelab.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename | lower}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          allowEmpty: true
      ignoreDifferences:
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
