apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: webservice-postgresql
  namespace: webservice
spec:
  instances: 1
  logLevel: warning
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: webservice
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 16
  managed:
    roles:
      - name: webservice
        superuser: true
        createdb: true
        login: true
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 40m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  storage:
    size: 1Gi
  walStorage:
    size: 1Gi
