apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: /CertManager
        property: API-KEY
      secretKey: api-key
    - remoteRef:
        key: /CertManager
        property: API-EMAIL
      secretKey: email
  target:
    creationPolicy: Owner
    deletionPolicy: Merge
    name: cloudflare-api-key
