apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: kube-prometheus-stack
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: /kube-prometheus-stack/grafana
        property: user
      secretKey: user
    - remoteRef:
        key: /kube-prometheus-stack/grafana
        property: password
      secretKey: password
  target:
    creationPolicy: Owner
    deletionPolicy: Merge
    name: grafana-admin-credentials
