apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mogenius-operator-api-secret
  namespace: mogenius
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: /mogenius
        property: API_KEY
      secretKey: API_KEY
  target:
    creationPolicy: Owner
    deletionPolicy: Merge
    name: mogenius-operator-api-secret
