apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backup
  namespace: argo-workflows
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: /Postgres
        property: User
      secretKey: POSTGRES_USER
    - remoteRef:
        key: /Postgres
        property: Password
      secretKey: POSTGRES_PASSWORD
  target:
    creationPolicy: Owner
    deletionPolicy: Merge
    name: postgres-secret
