---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: default
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: external-secrets-operator
          key: token
