apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-connection
  namespace: webservice
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: /WebService
        property: PostgresConnectionString
      secretKey: PostgresConnectionString
  target:
    creationPolicy: Owner
    deletionPolicy: Merge
    name: postgres-connection
