apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webservice-mcp-dev
  namespace: mogenius-dev
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: /mogenius/dev
        property: WEBSERVICE_API_KEY
      secretKey: API_KEY
  target:
    creationPolicy: Owner
    deletionPolicy: Merge
    name: webservice-mcp
