apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.4.2
    chart: argo-cd
    helm:
      valuesObject:
        global:
          networkPolicy:
            create: true
          logging:
            format: json
            level: warn # One of: `debug`, `info`, `warn` or `error`

        # deactivate unused features
        dex:
          enabled: false
        notifications:
          enabled: false

        server:
          resources:
            requests:
              cpu: 23m
              memory: 140M
          httproute:
            enabled: true
            parentRefs:
              - name: cilium-gateway
                namespace: cilium
            hostnames:
              - argocd.hankeln.work
          extraArgs:
            - --insecure

        repoServer:
          resources:
            requests:
              cpu: 70m
              memory: 120M

        applicationSet:
          resources:
            requests:
              cpu: 15m
              memory: 70M
        configs:
          cm:
            exec.enabled: "true"
          params:
            controller.diff.server.side: "true"
