apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: hankeln
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.15.2
    chart: cert-manager
    helm:
      valuesObject:
        installCRDs: true
        dns01RecursiveNameservers: "jaime.ns.cloudflare.com:53,zelda.ns.cloudflare.com:53"
        dns01RecursiveNameserversOnly: true
