apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  destination:
    name: in-cluster
    namespace: cilium
  source:
    repoURL: https://helm.cilium.io/
    targetRevision: 1.17.6
    chart: cilium
    helm:
      valuesObject:
        hubble:
          tls:
            enabled: false
          metrics:
            enabled:
              - dns:query
              - drop:labelsContext=source_namespace,destination_namespace
              - tcp
              - flow:labelsContext=source_namespace,destination_namespace
          relay:
            enabled: true
            replicas: 1
          ui:
            enabled: true
            ingress:
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
                gethomepage.dev/description: Hubble
                gethomepage.dev/enabled: 'true'
                gethomepage.dev/group: Observability
                gethomepage.dev/icon: cilium.png
                gethomepage.dev/name: Hubble
              className: nginx
              enabled: true
              hosts:
                - hubble.hankeln.work
              tls:
                - hosts:
                    - hubble.hankeln.work
                  secretName: hubble-tls
        ipv4NativeRoutingCIDR: 10.42.0.0/16
        ipam:
          operator:
            clusterPoolIPv4PodCIDRList:
              - 10.42.0.0/16
        operator:
          replicas: 1
