apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  destination:
    name: in-cluster
    namespace: cilium
  source:
    repoURL: https://helm.cilium.io/
    targetRevision: 1.18.6
    chart: cilium
    helm:
      valuesObject:
        k8sServiceHost: localhost
        k8sServicePort: 7445
        kubeProxyReplacement: true
        ipam:
          mode: kubernetes
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
            cleanCiliumState:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup

        operator:
          replicas: 1

        hubble:
          tls:
            enabled: false
          metrics:
            enabled:
              - dns:query
              - drop:labelsContext=source_namespace,destination_namespace
              - tcp
              - flow:labelsContext=source_namespace,destination_namespace
            dashboards:
              enabled: true
            serviceMonitor:
              enabled: true
          relay:
            enabled: true
            replicas: 1
          ui:
            enabled: true
            ingress:
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
                gethomepage.dev/description: Hubble
                gethomepage.dev/enabled: "true"
                gethomepage.dev/group: Observability
                gethomepage.dev/icon: cilium.png
                gethomepage.dev/name: Hubble
              className: nginx
              enabled: true
              hosts:
                - hubble.hankeln.work
              tls:
                - hosts:
                    - hubble.hankeln.work
                  secretName: hubble-tls
        gatewayAPI:
          enabled: true
