apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-ui
  namespace: argocd
spec:
  project: hankeln
  destination:
    name: in-cluster
    namespace: docker-ui
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://helm.joxit.dev
    targetRevision: 1.1.3
    chart: docker-registry-ui
    helm:
      valuesObject:
        ui:
          dockerRegistryUrl: https://docker-registry.hankeln.work
          image: joxit/docker-registry-ui:2.5.7 # renovate
          deleteImages: true
          showContentDigest: true
          ingress:
            enabled: true
            host: docker.hankeln.work
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
            tls:
              - hosts:
                  - docker.hankeln.work
                secretName: docker-ui-tls
          service:
            port: 8080
          title: "Private Registry"
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"

        registry:
          enabled: true
          image: registry:2.8.3 # renovate
          extraEnv:
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
              value: '["*"]'
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
              value: '[HEAD,GET,OPTIONS,DELETE]'
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
              value: '[Authorization, Accept]'
          ingress:
            enabled: true
            path: /
            host: docker-registry.hankeln.work
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
              nginx.ingress.kubernetes.io/proxy-body-size: 1024m
            tls:
              - hosts:
                  - docker-registry.hankeln.work
                secretName: docker-registry-tls
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          dataVolume:
            persistentVolumeClaim:
              claimName: docker-registry
