apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets-operator
    server: https://kubernetes.default.svc
  project: hankeln
  revisionHistoryLimit: 1
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.20.3
    helm:
      releaseName: external-secrets-operator
      valuesObject:
        resources:
          requests:
            cpu: 30m
            memory: 130M
          limits:
            cpu: 70m
            memory: 300M
        webhook:
          create: false
          resources:
            requests:
              cpu: 10m
              memory: 30M
            limits:
              cpu: 10m
              memory: 60M
        certController:
          create: false
          resources:
            requests:
              cpu: 10m
              memory: 30M
            limits:
              cpu: 10m
              memory: 60M
