apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: focalboard
  namespace: argocd
  finalizers:
  - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: focalboard
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    repoURL: https://helm.mattermost.com
    targetRevision: 0.5.0
    chart: mattermost/focalboard
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: board.hankeln.work
