apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: default
  project: hankeln
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    targetRevision: v1.4.1
    path: config/crd
