apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  destination:
    name: in-cluster
    namespace: gatus
  source:
    repoURL: https://twin.github.io/helm-charts
    targetRevision: 1.3.1
    chart: gatus
    helm:
      valuesObject:
        podLabels:
          network-policy/deny-all: "true"
          network-policy/ingess-nginx-port: "8080"
          network-policy/egress-dns: "true"
          network-policy/egress-world: "true"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
            kubernetes.io/ingress.class: nginx
            gethomepage.dev/description: Gatus
            gethomepage.dev/enabled: 'true'
            gethomepage.dev/group: Observability
            gethomepage.dev/icon: gatus.png
            gethomepage.dev/name: Gatus
            gethomepage.dev/pod-selector: ''
            gethomepage.dev/widget.type: gatus
            gethomepage.dev/widget.url: https://status.hankeln.work
          hosts:
            - status.hankeln.work
          tls:
            - secretName: gatus-tls
              hosts:
                - status.hankeln.work
        config:
          endpoints:
            - name: Hassio
              url: https://hassio.hankeln.work
              interval: 60s
              conditions:
                - "[STATUS] == 200"
                - "[CERTIFICATE_EXPIRATION] > 168h"
              alerts:
                - type: ntfy
                  description: "homeassistant is down"
                  send-on-resolved: true
            - name: WebService
              url: https://web.hankeln.work/api/_health
              interval: 60s
              conditions:
                - "[STATUS] == 200"
                - "[CERTIFICATE_EXPIRATION] > 48h"
              alerts:
                - type: ntfy
                  description: "webservice is down"
                  send-on-resolved: true
            - name: Gitea
              url: https://git.hankeln.work/api/healthz
              interval: 60s
              conditions:
                - "[STATUS] == 200"
                - "[CERTIFICATE_EXPIRATION] > 48h"
              alerts:
                - type: ntfy
                  description: "gitea is down"
                  send-on-resolved: true
            - name: External DNS
              url: "8.8.8.8"
              dns:
                query-name: "hankeln.work"
                query-type: "A"
              conditions:
                - "[CONNECTED] == true"
                - "[DNS_RCODE] == NOERROR"
              alerts:
                - type: ntfy
                  description: "external is down"
                  send-on-resolved: false
          alerting:
            ntfy:
              topic: "alerts"
              priority: 2
              url: https://ntfy.hankeln.work
              click: https://status.hankeln.work/
              default-alert:
                enabled: true
                failure-threshold: 1
                send-on-resolved: true
