apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  destination:
    name: in-cluster
    namespace: gitea
  source:
    repoURL: https://dl.gitea.io/charts
    targetRevision: 12.5.0
    chart: gitea
    helm:
      valuesObject:
        deployment:
          labels:
            network-policy/egress-dns: "true"
            network-policy/ingress-nginx-port: "3000"
            network-policy/egress-world: "true"
            network-policy/egress-postgres: "true"
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
            cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
          className: nginx
          hosts:
            - host: git.hankeln.work
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: gitea-tls
              hosts:
                - git.hankeln.work
        persistence:
          create: false
          claimName: "gitea-volume-claim"
          volumeName: "gitea-volume"
        valkey-cluster:
          enabled: false
        postgresql-ha:
          enabled: false
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
        valkey:
          enabled: false
          global:
            valkey:
              password: changemeplease
        gitea:
            config:
              database:
                DB_TYPE: postgres
                HOST: gitea-postgresql-rw.gitea.svc.cluster.local:5432
                NAME: gitea
                USER:
                  valueFrom:
                    secretKeyRef:
                      name: gitea-postgresql-app
                      key: username
                PASSWD:
                  valueFrom:
                    secretKeyRef:
                      name: gitea-postgresql-app
                      key: password
                SSL_MODE: disable
