apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  destination:
    name: in-cluster
    namespace: gitea
  source:
    repoURL: https://dl.gitea.io/charts
    targetRevision: 11.0.1
    chart: gitea
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
            cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
          className: nginx
          hosts:
            - host: git.hankeln.work
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: gitea-tls
              hosts:
                - git.hankeln.work
        persistence:
          create: false
          claimName: "gitea-volume-claim"
          volumeName: "gitea-volume"
        redis-cluster:
          enabled: false
        postgresql-ha:
          enabled: false
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "600m"
        actions:
          enabled: true
          provisioning:
            enabled: true
            ttlSecondsAfterFinished: null
          statefulset:
            resources:
              requests:
                memory: "200Mi"
                cpu: "50m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
