apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: hankeln
  destination:
    name: in-cluster
    namespace: homepage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: http://jameswynn.github.io/helm-charts
    targetRevision: 2.1.0
    chart: homepage
    helm:
      valuesObject:
        enableRbac: true

        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
              kubernetes.io/ingress.class: nginx
            ingressClassName: nginx
            hosts:
              - host: hankeln.work
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - hankeln.work
                secretName: homepage-tls
        env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            # This value must be set
            # ref: https://gethomepage.dev/installation/#homepage_allowed_hosts
            value: hankeln.work
        config:
          # To use an existing ConfigMap uncomment this line and specify the name
          # useExistingConfigMap: existing-homepage-configmap
          bookmarks:
            - Developer:
                - Github:
                    - abbr: GH
                      href: https://github.com/
                - Stack Overflow:
                    - abbr: SO
                      href: https://stackoverflow.com/
                - GitLab:
                    - abbr: GL
                      href: https://gitlab.com/
                - Docker Hub:
                    - abbr: DH
                      href: https://hub.docker.com/
          services:
            - Home Automation:
                - NAS:
                    href: http://192.168.1.112:8000/portal/
                    description: Network Attached Storage
                - Home Assistant:
                    href: https://hassio.hankeln.work/
                    description: Home automation platform
                - Free Box:
                    href: http://mafreebox.freebox.fr/
                    description: Freebox management interface
          widgets:
            - resources:
                backend: kubernetes
                expanded: true
                cpu: true
                memory: true
            - search:
                provider: duckduckgo
                target: _blank
            - kubernetes:
                cluster:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
                  label: "cluster"
                nodes:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
            - datetime:
                format:
                  dateStyle: long
                  timeStyle: short
                  hour12: false
          kubernetes:
            mode: cluster
          docker: {}
          settings: {}
          settingsString: |
            title: "Hankeln Homelab Dashboard"
            headerStyle: boxed
            theme: dark
            iconStyle: colored
            layout:
              Home Automation:
              Observability:
