apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: hankeln
  destination:
    name: in-cluster
    namespace: homepage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: http://jameswynn.github.io/helm-charts
    targetRevision: 2.1.0
    chart: homepage
    helm:
      valuesObject:
        enableRbac: true

        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
              kubernetes.io/ingress.class: nginx
            ingressClassName: nginx
            hosts:
              - host: homepage.hankeln.work
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - homepage.hankeln.work
                secretName: homepage-tls
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              # This value must be set
              # ref: https://gethomepage.dev/installation/#homepage_allowed_hosts
              value: https://homepage.hankeln.work
