apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: homeassistant
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: oci://ghcr.io/tibuntu/charts/homeassistant-kubernetes-rbac
    targetRevision: v1.7.0
    path: .
    helm:
      valuesObject: {}
