apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://kube-the-home.github.io/generic-helm/
    targetRevision: 2.6.0
    chart: generic
    helm:
      valuesObject:
        image:
          registry: ghcr.io
          repository: gethomepage/homepage
          tag: v2.1.1 # datasource=docker depName=ghcr.io/gethomepage/homepage versioning=docker
        application:
          port: 3000
          probe:
            path: /api/healthcheck
          additionalLabels:
            network-policy/deny-all: "true"
            network-policy/egress-dns: "true"
            network-policy/egress-ingress-controller: "true"
            network-policy/ingress-port: "3000"
        route:
          enabled: true
          parentRefs:
            - name: cilium-gateway
              namespace: cilium
          hostnames:
            - dash.hankeln.work
        env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: "*" # healthchecks use the pod ip as host...
          - name: LOG_TARGETS
            value: stdout
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
        configMaps:
          - name: homepage
            mountPath: /app/config
            data:
              settings.yaml: |
                title: "Hankeln Homelab Dashboard"
                headerStyle: boxed
                theme: dark
                iconStyle: colored
                layout:
                  Home Automation:
                  Platform:
              bookmarks.yaml: |
                - Developer:
                    - Github:
                        - abbr: GH
                          href: https://github.com/
                    - Stack Overflow:
                        - abbr: SO
                          href: https://stackoverflow.com/
                    - GitLab:
                        - abbr: GL
                          href: https://gitlab.com/
                    - Docker Hub:
                        - abbr: DH
                          href: https://hub.docker.com/
              services.yaml: |
                - Platform:
                    - Gatus:
                        href: https://status.hankeln.work
                        description: Status monitoring
                        icon: gatus.png
                        widget:
                          type: gatus
                          url: https://status.hankeln.work
                    - Prometheus:
                        href: http://prometheus.hankeln.work
                        description: Metrics monitoring
                        icon: prometheus.png
                        widget:
                          type: prometheus
                          url: http://prometheus.hankeln.work
                    - Hubble:
                        href: https://hubble.hankeln.work
                        description: Cilium, Hubble
                        icon: cilium.png
                - Home Automation:
                    - NAS:
                        href: http://192.168.1.112:8000/portal/
                        description: Network Attached Storage
                    - Home Assistant:
                        href: https://hassio.hankeln.work/
                        description: Home automation platform
                    - Free Box:
                        href: http://mafreebox.freebox.fr/
                        description: Freebox management interface
              widgets.yaml: |
                - search:
                    provider: duckduckgo
                    target: _blank
                - datetime:
                    format:
                      dateStyle: long
                      timeStyle: short
                      hour12: false
              kubernetes.yaml: |
                ---
              proxmox.yaml: |
                ---
              docker.yaml: |
                ---
              custom.css: ""
              custom.js: ""
        securityContext:
          pod:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          container:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
