apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
  source:
    # Chart: https://github.com/kagent-dev/kagent/tree/main/helm/kagent
    # Values: https://github.com/kagent-dev/kagent/blob/main/helm/kagent/values.yaml
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm/kagent
    targetRevision: 0.9.9
    path: .
    helm:
      valuesObject:
        providers:
          default: ollama
          ollama:
            provider: Ollama
            model: "qwen2.5:7b"
            config:
              host: ollama.kagent.svc.cluster.local:11434
              options:
                num_ctx: "64000"

        k8s-agent:
          enabled: false
        kgateway-agent:
          enabled: false
        istio-agent:
          enabled: false
        promql-agent:
          enabled: false
        observability-agent:
          enabled: false
        argo-rollouts-agent:
          enabled: false
        helm-agent:
          enabled: false
        cilium-policy-agent:
          enabled: false
        cilium-manager-agent:
          enabled: false
        cilium-debug-agent:
          enabled: true
