apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
  source:
    # Chart: https://github.com/kagent-dev/kagent/tree/main/helm/kagent-crds
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm/kagent-crds
    targetRevision: 0.9.9
    path: .
