apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanboard
  namespace: argocd
  finalizers:
  - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: kanboard
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    repoURL: https://github.com/lukashankeln/Homelab.git
    targetRevision: main
    path: helm/kanboard
    helm:
      valuesObject:
        application:
          port: 80
        clusterip:
          enabled: true
        nodePort:
          enabled: true
          port: 32007
        ingress:
          enabled: true
          host: board.hankeln.work
