apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanboard
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: kanboard
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://kube-the-home.github.io/kanboard-helm/
    targetRevision: 1.0.0
    chart: kanboard
    helm:
      valuesObject:
        application:
          additionalLabels:
            network-policy/deny-all: "true"
            network-policy/ingess-nginx-port: "80"
          persistence:
            enabled: true
            persistentVolumeClaim:
              storageClass: nfs

        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
          host: board.hankeln.work
          tls:
            - hosts:
                - board.hankeln.work
              secretName: kanboard-tls
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
