apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanboard
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: kanboard
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    repoURL: https://kube-the-home.github.io/kanboard-helm/
    targetRevision: 0.2.4
    chart: kanboard
    helm:
      valuesObject:
        application:
          persistence:
            enabled: true
            persistentVolumeClaim:
              storageClass: nfs

        ingress:
          enabled: true
          host: board.hankeln.work
          tls:
            - hosts:
                - board.hankeln.work
              secretName: kanboard-tls
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
