apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanboard
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: kanboard
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://kube-the-home.github.io/kanboard-helm/
    targetRevision: 1.2.1
    chart: kanboard
    helm:
      valuesObject:
        application:
          additionalLabels:
            network-policy/deny-all: "true"
            network-policy/ingress-port: "80"
          persistence:
            enabled: true
            persistentVolumeClaim:
              storageClass: nfs

        route:
          enabled: true
          parentRefs:
            - name: cilium-gateway
              namespace: cilium
          hostnames:
            - board.hankeln.work
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
