---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-descheduler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-descheduler
    name: in-cluster
  project: mogenius
  revisionHistoryLimit: 1
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://kubernetes-sigs.github.io/descheduler/
    targetRevision: 0.36.0
    # Repository: https://github.com/kubernetes-sigs/descheduler
    # ArtifactHub: https://artifacthub.io/packages/helm/descheduler/descheduler
    # Values: https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/values.yaml
    chart: descheduler
    helm:
      releaseName: kube-descheduler
      valuesObject:
        kind: Deployment
        deschedulingInterval: 12h
        resources:
          requests:
            cpu: 30m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        podSecurityContext:
          runAsGroup: 1000
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        cmdOptions:
          v: 4
        deschedulerPolicy:
          profiles:
            - name: default
              pluginConfig:
                - name: DefaultEvictor
                  args:
                    ignorePvcPods: false
                    evictLocalStoragePods: true
                    nodeFit: true # https://github.com/kubernetes-sigs/descheduler/blob/release-1.31/README.md#node-fit-filtering
                    namespaces:
                      exclude:
                        - kube-system
                        - cilium
                        - vault
                - name: RemoveDuplicates
                - name: RemovePodsHavingTooManyRestarts
                  args:
                    podRestartThreshold: 100
                    includingInitContainers: true
                - name: RemovePodsViolatingNodeAffinity
                  args:
                    nodeAffinityType:
                      - requiredDuringSchedulingIgnoredDuringExecution
                - name: RemovePodsViolatingNodeTaints
                - name: RemovePodsViolatingInterPodAntiAffinity
                - name: RemovePodsViolatingTopologySpreadConstraint
                - name: LowNodeUtilization
                  args:
                    thresholds:
                      cpu: 30
                      memory: 30
                    targetThresholds:
                      cpu: 50
                      memory: 50
              plugins:
                balance:
                  enabled:
                    - RemoveDuplicates
                    - RemovePodsViolatingTopologySpreadConstraint
                    - LowNodeUtilization
                deschedule:
                  enabled:
                    - RemovePodsHavingTooManyRestarts
                    - RemovePodsViolatingNodeTaints
                    - RemovePodsViolatingNodeAffinity
                    - RemovePodsViolatingInterPodAntiAffinity
        serviceMonitor:
          enabled: true
        service:
          enabled: true
