apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mogenius-operator
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 0
  destination:
    name: in-cluster
    namespace: mogenius
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  ignoreDifferences:
    - group: "apps"
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/valkey-password-checksum
    - kind: Secret
      name: mogenius-operator-valkey
      jsonPointers:
        - /data/valkey-password
  source:
    repoURL: https://helm.mogenius.com/public
    targetRevision: v2.18.0
    chart: mogenius-operator
    helm:
      valuesObject:
        fullnameOverride: mogenius-operator
        revisionHistoryLimit: 1
        global:
          cluster_name: homelab
