apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: hankeln
  destination:
    name: in-cluster
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.4
    chart: ingress-nginx
    helm:
      valuesObject:
        controller:
          name: controller
          extraArgs:
            v: 1
          config:
            error-log-level: warn
            access-log-off: true
