apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.4
    chart: ingress-nginx
    helm:
      valuesObject:
        controller:
          name: "controller"