apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate-operator
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: renovate-operator
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://helm.mogenius.com/public
    targetRevision: 1.17.3
    chart: renovate-operator
    helm:
      valuesObject:
        route:
          enabled: true
          parentRefs:
            - name: cilium-gateway
              namespace: cilium
          hostnames:
            - renovate.hankeln.work

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
          dashboard:
            enabled: true
            annotations:
              argocd.argoproj.io/sync-options: ServerSideApply=true
              grafana_folder: "Supporting Services"
            labels:
              grafana_dashboard: "1"
