apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seq-application
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: seq
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    repoURL: https://helm.datalust.co
    targetRevision: 2024.3.1
    chart: seq
    helm:
      valuesObject:
        baseURI: https://seq.hankeln.work/

        ingress:
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
          tls:
            - hosts:
                - seq.hankeln.work
                - in.seq.hankeln.work
              secretName: seq-tls

        ui:
          ingress:
            enabled: true
            path: /
            hosts:
              - seq.hankeln.work
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer

        ingestion:
          ingress:
            enabled: true
            path: /
            hosts:
              - in.seq.hankeln.work
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "TCP"
              nginx.ingress.kubernetes.io/proxy-buffering: "on"
              nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
              nginx.ingress.kubernetes.io/proxy-buffers-number: "4"

        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"
