apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seq-application
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: seq
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    repoURL: https://helm.datalust.co
    targetRevision: 2024.1.1
    chart: seq
    helm:
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: seq-tls
            hosts:
              - seq.hankeln.work
          - secretName: seq-ingest-tls
            hosts:
              - ingestion.seq.hankeln.work

      ui:
        ingress:
          enabled: true
          path: /
          hosts:
            - seq.hankeln.work

      ingestion:
        ingress:
          enabled: true
          path: /
          hosts:
            - ingestion.seq.hankeln.work
