apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skooner
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: skooner
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://kube-the-home.github.io/skooner-helm/
    targetRevision: 0.2.1
    chart: skooner
    helm:
      valuesObject:
        route:
          enabled: true
          parentRefs:
            - name: cilium-gateway
              namespace: cilium
          hostnames:
            - skooner.hankeln.work
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "100m"
