apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skooner
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: skooner
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://kube-the-home.github.io/skooner-helm/
    targetRevision: 0.1.1
    chart: skooner
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
          host: skooner.hankeln.work
          tls:
            - hosts:
                - skooner.hankeln.work
              secretName: skooner-tls
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "100m"
