apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: too-restful-api
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: too-restful-api
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://kube-the-home.github.io/too-restful-api/
    targetRevision: 1.0.3
    chart: too-restful-api
    helm:
      valuesObject:
        route:
          enabled: true
          parentRefs:
            - name: cilium-gateway
              namespace: cilium
          hostnames:
            - json.hankeln.work
        resources:
          requests:
            memory: "25Mi"
            cpu: "10m"
          limits:
            memory: "50Mi"
            cpu: "20m"
        additionalItems:
          - dev-api-configmap
