apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: hankeln
  revisionHistoryLimit: 1
  destination:
    name: in-cluster
    namespace: unifi
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://kube-the-home.github.io/generic-helm/
    targetRevision: 2.4.0
    chart: generic
    helm:
      valuesObject:
        image:
          registry: ghcr.io
          repository: unihosted/unifi-os-server-docker
          tag: 5.1.21 # datasource=docker depName=ghcr.io/unihosted/unifi-os-server-docker
        application:
          port: 443
          strategy: Recreate
          probe:
            startup:
              enabled: false
            readiness:
              enabled: false
            liveness:
              enabled: false
        clusterip:
          enabled: true
          port: 443
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
          - name: TZ
            value: Europe/Amsterdam
          - name: MONGO_INTERNAL
            value: "false"
          - name: UOS_SYSTEM_IP
            value: "127.0.0.1"
          - name: EXPOSE_NETWORK_APP
            value: "true"
        securityContext:
          pod:
            runAsUser: 0
          container:
            privileged: true
            capabilities:
              add:
                - NET_RAW
                - NET_ADMIN
        initContainers:
          - name: init-config-dir
            image: alpine:3.22
            command: ["sh", "-c", "mkdir -p /data/unifi-core/config/http"]
            volumeMounts:
              - name: unifi-data
                mountPath: /data
                subPath: data
        volumeMounts:
          - name: cgroup
            mountPath: /sys/fs/cgroup
          - name: unifi-data
            mountPath: /var/lib/uosserver
            subPath: uosserver
          - name: unifi-data
            mountPath: /var/lib/unifi
            subPath: unifi
          - name: unifi-data
            mountPath: /data
            subPath: data
          - name: run
            mountPath: /run
          - name: tmp
            mountPath: /tmp
          - name: journal
            mountPath: /var/lib/journal
          - name: unifi-tmp
            mountPath: /var/opt/unifi/tmp
        volumes:
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup
              type: Directory
          - name: unifi-data
            persistentVolumeClaim:
              claimName: unifi-data
          - name: run
            emptyDir: {}
          - name: tmp
            emptyDir: {}
          - name: journal
            emptyDir: {}
          - name: unifi-tmp
            emptyDir: {}
