apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  source:
    # Repository: https://github.com/louislam/uptime-kuma
    # Artifacthub: https://artifacthub.io/packages/helm/uptime-kuma/uptime-kuma
    # Values: https://github.com/dirsigler/uptime-kuma-helm/blob/main/charts/uptime-kuma/values.yaml
    repoURL: https://dirsigler.github.io/uptime-kuma-helm
    targetRevision: 2.17.0
    chart: uptime-kuma
    helm:
      releaseName: uptime-kuma
      valuesObject:
        image:
          tag: 1.23.4
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: status.hankeln.work
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: uptime-kuma-tls
              hosts:
                - status.hankeln.work
        podEnv:
          # a default port must be set. required by container
          - name: "UPTIME_KUMA_PORT"
            value: "3001"
          - name: "UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN"
            value: "1"
        volume:
          enabled: true
          size: 1Gi
        serviceAccount:
          create: true
          name: "uptime-kuma"
        serviceMonitor:
          enabled: true
