apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webservice-application
  namespace: argocd
  finalizers:
  - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: webservice
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    repoURL: https://github.com/lukashankeln/Homelab.git
    targetRevision: main
    path: helm/webapplication
    helm:
      values: |

        image:
          repository: "webservice"
          tag: "2.2.3"
        application:
          name: "webservice"
          port: 5090
          health:
            enabled: true
        nodePort:
          enabled: true
          port: 32000
        clusterip:
          enabled: true
        ingress:
          enabled: true
          host: "luha.server"
