apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webservice-application
  namespace: argocd
  finalizers:
  - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: webservice
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    repoURL: https://kube-the-home.github.io/generic-helm/
    targetRevision: 0.1.3
    chart: generic
    helm:
      valuesObject:
        image:
          registry: "docker-registry.hankeln.work"
          repository: "webservice"
          tag: "1.3.2"
        application:
          port: 5090
          labels:
            type: webservice
          health:
            enabled: true
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
            cpu: "200m"
        nodePort:
          enabled: true
          port: 32000
        ingress:
          enabled: true
          host: web.hankeln.work
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
          tls:
            - hosts:
                - web.hankeln.work
              secretName: webservice-tls
        env:
          - name: DOTNET_gcServer
            value: "1"
          - name: DOTNET_GCHeapCount
            value: "c"
        securityContext:
          container:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

