apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflow
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: workflow
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://kube-the-home.github.io/generic-helm/
    targetRevision: 1.0.0
    chart: generic
    helm:
      valuesObject:
        image:
          registry: docker-registry.hankeln.work
          repository: workflow/restapi
          tag: latest # datasource=docker depName=docker-registry.hankeln.work/workflow/restapi versioning=docker
          pullPolicy: Always
        application:
          port: 8080
          health:
            enabled: false
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "100m"
        ingress:
          enabled: true
          host: workflow.hankeln.work
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
          tls:
            - hosts:
                - workflow.hankeln.work
              secretName: workflow-tls
        env:
          # DOTNET
          - name: DOTNET_gcServer
            value: "1"
          - name: DOTNET_GCHeapCount
            value: "c"
          - name: ASPNETCORE_HTTP_PORTS
            value: "8080"
          - name: GlobalWorkflowSettings__Directory
            value: "/tmp"
        securityContext:
          container:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
        volumeMounts:
          - mountPath: /tmp
            name: tmp
        volumes:
          - name: tmp
            emptyDir: {}
