apiVersion: mogenius.com/v1alpha1
kind: PlatformConfig
metadata:
  name: platform
spec:
  gitOps:
    argocd:
      enabled: false
      project: mogenius
      chart:
        name: argocd
        namespace: argocd
