apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: kube-the-home
  namespace: renovate-operator
spec:
  metadata:
    labels:
      network-policy/egress-ingress-controller: "true"
      network-policy/egress-cluster-port-6379: "true"
      network-policy/egress-world: "true"
      network-policy/egress-dns: "true"
  schedule: "0,30 1-3 * * *"
  discoveryFilters:
    - "kube-the-home/*"
  image: renovate/renovate:43.227.1 # renovate
  provider:
    name: github
  githubAppReference:
    secretName: kube-the-home-renovate-secrets
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
  extraEnv:
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_GITHUB_COM_TOKEN
      valueFrom:
        secretKeyRef:
          name: kube-the-home-github-app-977470a8
          key: RENOVATE_TOKEN
  parallelism: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
  nodeSelector:
    kubernetes.io/hostname: server-luha-2
  webhook:
    enabled: true
