apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: kube-the-home
  namespace: renovate-operator
spec:
  templateRef:
    name: default
  schedule: "0,30 1-3 * * *"
  discoveryFilters:
    - "kube-the-home/*"
  provider:
    name: github
  githubAppReference:
    secretName: kube-the-home-renovate-secrets
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
  extraEnv:
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_GITHUB_COM_TOKEN
      valueFrom:
        secretKeyRef:
          name: kube-the-home-github-app-977470a8
          key: RENOVATE_TOKEN
