apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: lukashankeln
  namespace: renovate-operator
spec:
  templateRef:
    name: default
  schedule: "30 3,4 * * *"
  discoveryFilters:
    - lukashankeln/Commandline.Runner
    - lukashankeln/dotfiles
    - lukashankeln/glint
    - lukashankeln/mogenius-argocd
  provider:
    name: github
  skipForks: true
  githubAppReference:
    secretName: lukashankeln-renovate-secrets
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
  extraEnv:
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_REPORT_TYPE
      value: "logging"
    - name: RENOVATE_GITHUB_COM_TOKEN
      valueFrom:
        secretKeyRef:
          name: lukashankeln-github-app-6d375865
          key: RENOVATE_TOKEN
