apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: lukashankeln
  namespace: renovate-operator
spec:
  metadata:
    labels:
      network-policy/egress-ingress-controller: "true"
      network-policy/egress-cluster-port-6379: "true"
      network-policy/egress-world: "true"
      network-policy/egress-dns: "true"
  schedule: "30 3,4 * * *"
  discoveryFilters:
    - lukashankeln/Commandline.Runner
    - lukashankeln/dotfiles
    - lukashankeln/glint
    - lukashankeln/mogenius-argocd
  image: renovate/renovate:43.278.4 # renovate
  provider:
    name: github
  skipForks: true
  githubAppReference:
    secretName: lukashankeln-renovate-secrets
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
  extraEnv:
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_REPORT_TYPE
      value: "logging"
    - name: RENOVATE_GITHUB_COM_TOKEN
      valueFrom:
        secretKeyRef:
          name: lukashankeln-github-app-6d375865
          key: RENOVATE_TOKEN
  parallelism: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
  nodeSelector:
    kubernetes.io/hostname: server-luha-2
  webhook:
    enabled: true
