---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network-policies
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - namespace: webservice
          - namespace: workflow
          - namespace: postgres
          - namespace: dashy
          - namespace: gatus
  template:
    metadata:
      name: "network-policies-{{ namespace }}"
      namespace: argocd
    spec:
      project: hankeln
      source:
        repoURL: https://github.com/lukashankeln/Homelab.git
        path: network-policies
        targetRevision: main
        directory:
          recurse: true
      destination:
        name: in-cluster
        namespace: "{{ namespace }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
