apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-postgres
spec:
  endpointSelector:
    matchLabels:
      network-policy/egress-postgres: "true"
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: postgres
      toPorts:
        - ports:
            - port: "5432"
