name: "gitops-linter"
on:
  pull_request:
    branches: ["main"]

jobs:
  yamllint:
    uses: https://github.com/kube-the-home/github-actions/.github/workflows/yamllint.yaml@a4e300db6adb24b0f86b3fee25548b76dd18f999 # v1.4.4

  gitops-linter:
    uses: https://github.com/kube-the-home/github-actions/.github/workflows/gitops-linter.yaml@a4e300db6adb24b0f86b3fee25548b76dd18f999 # v1.4.4
