name: "gitops-linter"
on:
  pull_request:
    branches: ["main"]

jobs:
  yamllint:
    uses: https://github.com/kube-the-home/github-actions/.github/workflows/yamllint.yaml@2b44df6e69f5674627ef7a7b3c0ddd752781e6f3 # v1.4.6

  gitops-linter:
    uses: https://github.com/kube-the-home/github-actions/.github/workflows/gitops-linter.yaml@2b44df6e69f5674627ef7a7b3c0ddd752781e6f3 # v1.4.6
