name: "gitops-linter"
on:
  pull_request:
    branches: ["main"]

jobs:
  yamllint:
    uses: https://git.hankeln.work/Hankeln/github-actions/.github/workflows/yamllint.yaml@70b35bb255a89f5a9281934be8941da086031276 # v1.4.11

  gitops-linter:
    uses: https://git.hankeln.work/Hankeln/github-actions/.github/workflows/gitops-linter.yaml@70b35bb255a89f5a9281934be8941da086031276 # v1.4.11
