name: ArgoCD-Setup
on:
  push:
    branches: ["main"]
    paths: ["charts/argocd/**"]

env:
  KUBECONFIG_VALUE: ${{ secrets.KUBECONFIG_VALUE }}
  KUBECONFIG: /tmp/kube_config.yaml

jobs:
  argocd-setup:
    name: ArgoCD-Setup
    runs-on: ubuntu-latest
    container:
      image: docker-registry.hankeln.work/gitea-runner:1.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Build Kube Config
        run: |
          echo "${KUBECONFIG_VALUE}" | base64 -d > "${KUBECONFIG}"
          chmod go-r "${KUBECONFIG}"

      - name: Helm Dependency Build
        run: |
          cd charts/argocd
          export HELM_REPOSITORY_CONFIG="${PWD}/repositories.yaml"
          helm dependency build

      - name: Helm Upgrade
        run: |
          cd charts/argocd
          export HELM_REPOSITORY_CONFIG="${PWD}/repositories.yaml"
          helm upgrade --values ./values.yaml --namespace argocd argocd .
