name: "linting"
on:
  pull_request:
    branches: ["main"]

jobs:
  yamllint:
    name: "Yamllint"
    runs-on: ubuntu-latest
    container:
      image: docker-registry.hankeln.work/gitea-runner:1.0.6
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Yamllint"
        uses: karancode/yamllint-github-action@v3.0.0
        with:
          yamllint_file_or_dir: "."
