name: ArgoCD-Template
on:
  pull_request:
    branches: ["main"]
    paths: ["argocd/**"]

jobs:
  argocd-template:
    name: ArgoCD-Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Dependency Build
        run: |
          cd argocd
          export HELM_REPOSITORY_CONFIG="${PWD}/repositories.yaml"
          helm dependency build

      - name: Helm Template
        run: |
          set -eu
          cd argocd
          export HELM_REPOSITORY_CONFIG="${PWD}/repositories.yaml"
          helm template --values ./values.yaml . > out.yaml
