name: Cilium-Template
on:
  pull_request:
    branches: ["main"]
    paths: ["charts/cilium/**"]

jobs:
  cilium-template:
    name: Cilium-Template
    runs-on: ubuntu-latest
    container:
      image: docker-registry.hankeln.work/gitea-runner:1.0.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Dependency Build
        run: |
          cd charts/cilium
          export HELM_REPOSITORY_CONFIG="${PWD}/repositories.yaml"
          helm dependency build

      - name: Helm Template
        run: |
          set -eu
          cd charts/cilium
          export HELM_REPOSITORY_CONFIG="${PWD}/repositories.yaml"
          helm template --values ./values.yaml . > out.yaml
