name: "Yamllint"
on:
  pull_request:
    branches: ["main"]

jobs:
  yamllint:
    name: "Yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Yamllint"
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: "."
