apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webservice-certificate
  namespace: webservice
spec:
  secretName: webservice-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  commonName: web.hankeln.work
  dnsNames:
  - web.hankeln.work
