apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanboard-certificate
  namespace: kanboard
spec:
  secretName: kanboard-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  commonName: board.hankeln.work
  dnsNames:
  - board.hankeln.work
