apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skooner-certificate
  namespace: skooner
spec:
  secretName: skooner-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  commonName: skooner.hankeln.work
  dnsNames:
  - skooner.hankeln.work
