apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-volume
  namespace: gitea
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /Kubernetes/gitea
    server: nas.hankeln.work

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-volume-claim
  namespace: gitea
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-certificate
  namespace: gitea
spec:
  secretName: gitea-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  commonName: git.hankeln.work
  dnsNames:
  - git.hankeln.work
