apiVersion: v1
kind: PersistentVolume
metadata:
  name: kanboard-volume
  namespace: kanboard
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/Kubernetes/kanboard
    server: nas.hankeln.work
