apiVersion: v1alpha1
kind: KubeAPIServerConfig
image: registry.k8s.io/kube-apiserver:v1.36.4 # renovate
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
image: registry.k8s.io/kube-controller-manager:v1.36.4 # renovate
---
apiVersion: v1alpha1
kind: KubeProxyConfig
image: registry.k8s.io/kube-proxy:v1.36.4 # renovate
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
image: registry.k8s.io/kube-scheduler:v1.36.4 # renovate
