apiVersion: v1alpha1
kind: KubeAPIServerConfig
resources:
  requests:
    cpu: 200m
    memory: 4Gi
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
resources:
  requests:
    cpu: 200m
    memory: 512Mi
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
resources:
  requests:
    cpu: 200m
    memory: 512Mi
