apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gitea-policy
  namespace: gitea
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: ingress-nginx
      toPorts:
        - ports:
            - port: "3000"
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: gitea-runner
  egress:
    - toFQDNs:
        - matchName: github.com
