apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: act-runner
  labels:
    app: act-runner
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: act-runner
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
