apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: postgres-backup-scheduled
  namespace: argo-workflows
spec:
  schedule: "0 23 * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    entrypoint: template
    serviceAccountName: argo-workflow-executor
    templates:
      - name: template
        steps:
          - - name: backup
              templateRef:
                name: postgres-backup-base
                template: backup
