apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: postgres-backup-base
  namespace: argo-workflows
spec:
  entrypoint: backup
  serviceAccountName: argo-workflow-executor
  volumes:
    - name: backup-pvc
      persistentVolumeClaim:
        claimName: postgres-backup
  templates:
    - name: backup
      metadata:
        labels:
          network-policy/egress-postgres: "true"
          network-policy/egress-dns: "true"
      script:
        image: postgres:16.6
        volumeMounts:
          - name: backup-pvc
            mountPath: /mnt/backup
        env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: PGDATABASE
            value: "webservice"
          - name: POSTGRES_HOST
            value: "webservice-postgresql-rw.webservice.svc.cluster.local"
        command: [sh, -c]
        args:
          - |
            set -eu

            echo "Starting backup at $(date)"
            pg_dump -h $POSTGRES_HOST > /mnt/backup/database_$(date +%d-%m-%Y_%H-%M).sql
            echo "Backup completed at $(date)"

            echo "Deleting old backups, keeping only the 10 most recent backups"
            ls -tp /mnt/backup/database_*.sql | grep -v '/$' | tail -n +11 | xargs -I {} rm -- {}
            echo "Old backups deleted at $(date)"
