apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: postgres-backup-base
  namespace: argo-workflows
spec:
  entrypoint: backup
  serviceAccountName: argo-workflow-executor
  volumes:
    - name: backup-pvc
      persistentVolumeClaim:
        claimName: postgres-backup
  templates:
    - name: backup
      metadata:
        labels:
          network-policy/egress-postgres: "true"
          network-policy/egress-dns: "true"
      script:
        image: postgres:16.6
        volumeMounts:
          - name: backup-pvc
            mountPath: /mnt/backup
        env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: PGDATABASE
            value: "WebService"
          - name: POSTGRES_HOST
            value: "postgres-service.postgres.svc.cluster.local"
        command: [sh, -c]
        source: |
          pg_dump -h $POSTGRES_HOST > /mnt/backup/database_$(date +%H_%M_%d_%m_%Y).sql
