apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    app: webservice
    type: webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
      type: webservice
  template:
    metadata:
      labels:
        app: webservice
        type: webservice
    spec:
      containers:
      - name: webservice
        image: 192.168.178.43:31000/webservice:1.6.15
        env:
        - name: DOTNET_gcServer
          value: "1"
        - name: DOTNET_GCHeapCount
          value: "c"
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5090
        livenessProbe:
          httpGet:
            path: /api/_health
            port: 5090
          initialDelaySeconds: 3
          periodSeconds: 10