image:
  registry: ~
  repository: ~
  tag: ~
  pullPolicy: "IfNotPresent"

application:
  port: ~
  health:
    enabled: false
    path: "/api/_health"
    initialDelaySeconds: 30
    periodSeconds: 30
  labels: {}



securityContext:
  pod: {}
  container: {}

resources: {}

nodePort:
  enabled: false
  port: ~
  labels: {}

clusterip:
  enabled: false
  port: 8080
  labels: {}

ingress:
  enabled: false
  ingressClassName: "nginx"
  host: ~
  tls: []
  labels: {}

env: {}
