apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-ui
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-ui
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    repoURL: https://helm.joxit.dev
    targetRevision: 1.1.3
    chart: docker-registry-ui
    helm:
      values: |
        
        ui:
          title: "Private Registry"

---

apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  labels:
    app: docker-registry-ui
spec:
  type: NodePort
  ports:
   - port: 80
     nodePort: 32500
  selector:
   name: docker-registry-ui