image:
  registry: "docker.io"
  repository: "kanboard/kanboard"
  tag: "v1.2.35"
  pullPolicy: "IfNotPresent"

application:
  port: 80
  persistence: false


nodePort:
  enabled: false
  port: ~

clusterip:
  enabled: false
  port: 8080

ingress:
  enabled: false
  ingressClassName: "nginx"
  host: ~
  tls: ~

securityContext:
  pod: ~
  container: ~

resources: ~
