{{- $name := include "app.name" . -}}

{{- if or .Values.clusterip.enabled .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-clusterip
  {{- if .Values.clusterip.labels }}
  labels:
    {{- toYaml .Values.clusterip.labels | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: {{ .Values.clusterip.port }}
      targetPort: {{ .Values.application.port }}
{{- end }}
