{{- $name := include "app.name" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    {{- if .Values.application.labels }}
    {{- toYaml .Values.application.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
      {{- if .Values.application.labels }}
      {{- toYaml .Values.application.labels | nindent 6 }}
      {{- end }}
  {{- if .Values.securityContext.pod }}
  securityContext:
  {{- toYaml .Values.securityContext.pod | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        {{- if .Values.application.labels }}
        {{- toYaml .Values.application.labels | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.container }}
          securityContext:
          {{- toYaml .Values.securityContext.container | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
          {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.application.port }}
          {{- if .Values.application.health.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.application.health.path }}
              port: {{ .Values.application.port }}
            initialDelaySeconds: {{ .Values.application.health.initialDelaySeconds }}
            periodSeconds: {{ .Values.application.health.periodSeconds }}
          {{- end }}
