{{- $name := include "app.name" . -}}

{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-nodeport
  {{- if .Values.nodePort.labels }}
  labels:
    {{- toYaml .Values.nodePort.labels | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
   - port: {{ .Values.application.port }}
     nodePort: {{ .Values.nodePort.port }}
  selector:
   app: {{ $name }}
{{- end }}
