{{- $name := include "kanboard.name" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: LOG_DRIVER
          value: "stdout"
        ports:
          - containerPort: {{ .Values.application.port }}
        volumeMounts:
        - mountPath: /var/www/app/
          name: app-volume
      volumes:
      - name: app-volume
        emptyDir: {}
