{{- $name := include "kanboard.name" . -}}

{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $name }}
spec:
  type: NodePort
  ports:
   - port: {{ .Values.application.port }}
     nodePort: {{ .Values.nodePort.port }}
  selector:
   app: {{ $name }}
{{- end }}
