apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  labels:
    app: seq
    type: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
      type: logging
  template:
    metadata:
      labels:
        app: seq
        type: logging
    spec:
      containers:
      - name: seq
        image: datalust/seq:2024.1
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 80
          - containerPort: 5341
        env:
        - name: ACCEPT_EULA
          value: "Y"
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "400Mi"
            cpu: "500m"


---
apiVersion: v1
kind: Service
metadata:
  name: seq-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32100
  selector:
    app: seq
    type: logging

---

apiVersion: v1
kind: Service
metadata:
  name: seq-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 5341 # Backend Port
      port: 5341       # Port  Service is exposing
  selector: 
    app: seq
    type: logging

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seq-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: "seq.luha.server"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seq-service
            port:
              number: 5341


