---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hankeln
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/lukashankeln/Homelab.git'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
