apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: external-secrets
  namespace: kube-prometheus-stack
spec:
  groups:
    - name: external-secrets
      rules:
        - alert: ClusterSecretStoreFailed
          expr: clustersecretstore_status_condition{status="False"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "ClusterSecretStore {{ $labels.name }} is not ready"
            description: "ClusterSecretStore {{ $labels.name }} has been in a failed state for more than 5 minutes."
