apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ip-pool
  namespace: cilium
spec:
  cidrs:
    - cidr: "192.168.1.10/30"
  serviceSelector:
    matchExpressions:
      - key: io.kubernetes.service.type
        operator: In
        values:
          - LoadBalancer
