apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: egress-ingress-controller
spec:
  endpointSelector:
    matchLabels:
      network-policy/egress-ingress-controller: "true"
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: contour
