apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ingress-controller-port-80
spec:
  endpointSelector:
    matchLabels:
      network-policy/ingress-controller-port: "80"
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: contour
      toPorts:
        - ports:
            - port: "80"
