cilium:
  hubble:
    tls:
      enabled: false
    metrics:
      enabled:
        - dns:query
        - drop:labelsContext=source_namespace,destination_namespace
        - tcp
        - flow:labelsContext=source_namespace,destination_namespace
    relay:
      enabled: true
      replicas: 1
    ui:
      enabled: true
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
        className: nginx
        enabled: true
        hosts:
          - hubble.hankeln.work
        tls:
          - hosts:
              - hubble.hankeln.work
            secretName: hubble-tls
  ipv4NativeRoutingCIDR: 10.42.0.0/16
  ipam:
    operator:
      clusterPoolIPv4PodCIDRList:
        - 10.42.0.0/16
  operator:
    replicas: 1
