argo-cd:
  global:
    networkPolicy:
      create: true
    logging:
      format: json
      level: warn # One of: `debug`, `info`, `warn` or `error`

  # deactivate unused features
  dex:
    enabled: false
  notifications:
    enabled: false

  server:
    certificate:
      enabled: true
      domain: argocd.hankeln.work
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-dns01-issuer
    resources:
      requests:
        cpu: 23m
        memory: 140M
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.hankeln.work
      tls: true
      extraPaths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: argocd-server
              port:
                name: http
    extraArgs:
      - --insecure

  repoServer:
    resources:
      requests:
        cpu: 70m
        memory: 120M

  applicationSet:
    resources:
      requests:
        cpu: 15m
        memory: 70M
  configs:
    cm:
      exec.enabled: "true"
    params:
      controller.diff.server.side: "true"
