apiVersion: v1
kind: ServiceAccount
metadata:
  name: homeassistant-kubernetes-integration
  namespace: homeassistant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homeassistant-kubernetes-integration
rules:
  # Read permissions for monitoring
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  # Write permissions for control - including scaling
  - apiGroups: ["apps"]
    resources:
      ["deployments", "deployments/scale", "statefulsets", "statefulsets/scale"]
    verbs: ["patch", "update", "get", "create", "delete"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["patch", "update", "get", "create", "delete"]
  # Additional permissions that might be needed
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  # Ensure we can access resources across all namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  # Additional StatefulSet permissions for better compatibility
  - apiGroups: ["apps"]
    resources: ["statefulsets/status"]
    verbs: ["get", "patch", "update"]
  # Batch API permissions for CronJobs
  - apiGroups: ["batch"]
    resources: ["cronjobs", "cronjobs/status", "jobs"]
    verbs: ["get", "list", "watch", "patch", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homeassistant-kubernetes-integration
subjects:
  - kind: ServiceAccount
    name: homeassistant-kubernetes-integration
    namespace: homeassistant
roleRef:
  kind: ClusterRole
  name: homeassistant-kubernetes-integration
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-kubernetes-integration-token
  namespace: homeassistant
  annotations:
    kubernetes.io/service-account.name: homeassistant-kubernetes-integration
type: kubernetes.io/service-account-token
