apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.12 # renovate
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.8 # renovate
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.2 # renovate
