apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webservice-application
  namespace: argocd
  finalizers:
  - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 1
  source:
    repoURL: https://github.com/lukashankeln/Homelab.git
    targetRevision: HEAD
    path: apps/webservice
  destination:
    server: https://kubernetes.default.svc
    namespace: webservice
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true